# Generated by Django 3.2.6 on 2021-08-21 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210821_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 8, 21, 7, 8, 25, 361172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='half_money',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
