# Generated by Django 3.2.7 on 2021-09-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210905_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_number',
            field=models.IntegerField(default=0, verbose_name='인증번호'),
        ),
    ]
