# Generated by Django 3.2.7 on 2021-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('store', models.CharField(max_length=255, verbose_name='store')),
                ('menu', models.CharField(max_length=255, verbose_name='menu')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('minPrice', models.CharField(max_length=255, verbose_name='minPrice')),
                ('delivTip', models.CharField(max_length=255, verbose_name='delivTip')),
                ('expDelivTime', models.CharField(max_length=255, verbose_name='expDelivTime')),
                ('openingHours', models.CharField(max_length=255, verbose_name='openingHours')),
            ],
        ),
    ]
