# Generated by Django 3.2.7 on 2021-09-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='WHAT',
            field=models.CharField(default='wtf', max_length=255, verbose_name='WHAT'),
        ),
    ]
