# Generated by Django 3.2.7 on 2021-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='minPrice',
            field=models.IntegerField(verbose_name='minPrice'),
        ),
    ]
