# Generated by Django 3.2.7 on 2021-09-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_stores_what'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='WHAT',
        ),
    ]
