# Generated by Django 3.2.7 on 2021-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210906_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
