# Generated by Django 3.2.7 on 2021-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_stores_minprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='minprice',
            field=models.CharField(max_length=255, verbose_name='minprice'),
        ),
    ]
