# Generated by Django 3.2.7 on 2021-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_stores_minprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
